# Generated by Django 2.0 on 2020-03-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_remove_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('sex', models.IntegerField(choices=[[0, '男'], [1, '女']], default=0)),
                ('icon', models.ImageField(default='icon/default.jpg', upload_to='icon')),
            ],
            options={
                'verbose_name': 'USer',
                'db_table': 't_user',
                'verbose_name_plural': 'USer',
            },
        ),
    ]
